### ISSUE TITLE
Issue 관련 질문

### ISSUE THREAD

**Issue by Longstick0** [Couch-Coders/6th-camp_us-be#105]
<br/>
## 질문이써열 🙋‍♀️
issiscv님께서 Swagger 문서 작성에 대한 이슈 #94 를 열어주셔서, 방금 이슈를 포함하여 풀리퀘스트를 보냈습니다.
제가 이해한 것으로는 자동으로 칸반보드에서 Issue가 merge가 된다면 자동으로 'to do'에서 'in progress'를 거쳐 'done'으로 이동하는 것으로 알고있는데, 저의 경우에는 자동으로 이동하지 않아, 제가 직접 강제로 이동했습니다. 혹시 제가 놓쳤던 과정이 있는지 확인해 주실 수 있나요?
<br/>

**Comment by issiscv** [comment]
아닙니다.
이슈는 close 될때만 to do 에서 done 으로 이동하고, progress 로 이동하는 경우는 re open 할때만 입니다.
PR 은 PR 요청이 있을 경우 바로 progress 로 이동 후 merge 하면 done 으로 이동합니다.

**Comment by Longstick0** [comment]
그러면 PR 요청을 할 때 Issue의 넘버를 반드시 붙여줘야만 progress 상태로 넘어가는 건가요?
