### ISSUE TITLE
MemberPostResponseDto 예외 처리 질문

### ISSUE THREAD

**Issue by Longstick0** [Couch-Coders/6th-camp_us-be#123]
- @issiscv 상운님 `MemberPostResponseDto`좀 봐주실 수 있나요? 
`try {
this.imgUrl = post.getPostImageList().get(0).toString();
        } catch (IndexOutOfBoundsException e) {
            this.imgUrl = "이미지가 없습니다.";
        }`
- 마이페이지에서 확인할 때는 post에 있는 모든 이미지를 가져올 필요가 없기 때문에 첫 이미지 한 장만 가져오고 싶어 위와 같이 코드를 작성했습니다. 그런데 이미지가 아예 없는 게시글도 존재하기 때문에 `IndexOutOfBoundsException`가 터졌는데요.
- 위 부분에서 dto에 이러한 코드가 들어가는 게 괜찮은지 아니면 service계층에서 이를 잡아줘야 할 지 피드백 부탁드립니다.
<br/>

**Comment by issiscv** [comment]
크게 문제가 되지는 않을거 같아요, 하지만 가독성을 위해 post.getPostImageList().isEmpty() 와 if else 로 더 간단하게 잡을 수 있지 않을까요?

**Comment by Longstick0** [comment]
아하 그런 간단한 방법이.. 한 번 돌려 생각했네요
