### ISSUE TITLE
배포용 yml, firebase 설정 파일 ec2 환경변수를 통해 받기

### ISSUE THREAD

**Issue by issiscv** [Couch-Coders/6th-camp_us-be#81]
보안을 위해 수정이 필요함.
- [ ] 배포용 yml, firebase 설정 파일 ec2 환경변수를 통해 받기

**Comment by Longstick0** [comment]
@issiscv 
상운님, EC2에 환경변수를 설정하는 걸 찾아보다가 'JASYPT'라는 라이브러리를 찾아서 이를 활용해 암호화를 하려고 합니다. 

다음을 참고하여 진행중입니다.
https://emgc.tistory.com/137

다량의 삽질로 인해 시간이 늦어 내일 다시 시도하겠습니닼
